#!/usr/bin/env python3
"""
Generate a C source file embedding all .bgf files from the tools directory.
Usage: python tools/generate_embedded_c.py <tools_dir> <out_c_path>
"""
import sys, os

def write_c(tools_dir, out_path):
    files = [f for f in os.listdir(tools_dir) if f.lower().endswith('.bgf')]
    with open(out_path, 'w') as out:
        out.write('/* Generated by generate_embedded_c.py */\n')
        out.write('#include "kernel.h"\n')
        out.write('#include "filesystem_new.h"\n')
        out.write('#include <stdint.h>\n')
        out.write('\n')
        out.write('extern int fs_runtime_ensure_newfs(void);\n')
        out.write('int install_embedded_files(void) {\n')
        out.write('    if (!fs_runtime_ensure_newfs()) return 0;\n')
        out.write('    int created = 0;\n')
        for fname in files:
            path = os.path.join(tools_dir, fname)
            var = fname.replace('.', '_')
            var = var.replace('-', '_')
            var = var.replace(' ', '_')
            arr_name = 'embedded_' + var
            # read bytes
            with open(path, 'rb') as f:
                data = f.read()
            out.write(f'static const unsigned char {arr_name}[] = {{\n')
            # write bytes in hex
            for i in range(0, len(data), 12):
                chunk = data[i:i+12]
                out.write('    ' + ', '.join('0x%02X' % b for b in chunk) + ',\n')
            out.write('};\n')
            out.write(f'static const unsigned int {arr_name}_len = {len(data)};\n')
            out.write('\n')
            out.write('    // Install %s into newfs root if missing\n' % fname)
            out.write('    {\n')
            out.write('        FInode tmp;\n')
            out.write('        if (vfs_stat("/%s", &tmp) < 0) {\n' % fname)
            out.write('        int fd = vfs_open("/%s", FS_O_WRITE | FS_O_CREATE | FS_O_TRUNC);\n' % fname)
            out.write('        if (fd >= 0) {\n')
            out.write('            int w = vfs_write(fd, (const char*)%s, (int)%s_len);\n' % (arr_name, arr_name))
            out.write('            vfs_close(fd);\n')
            out.write('            if (w == (int)%s_len) created = 1;\n' % arr_name)
            out.write('        }\n')
            out.write('        }\n')
            out.write('    }\n\n')
        out.write('    return created;\n')
        out.write('}\n')

if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: generate_embedded_c.py <tools_dir> <out_c_path>')
        sys.exit(2)
    write_c(sys.argv[1], sys.argv[2])
    print('Wrote', sys.argv[2])
